### ISSUE TITLE
ValueError when script run

### ISSUE THREAD

**Issue by python-b5** [Arc13/IndevProxy#2]
I get this error when running the script:
```Traceback (most recent call last):
  File "indevproxy.py", line 309, in <module>
    plugins='indevproxy.IndevProxyPlugin'
  File "C:\Users\dpgorman\AppData\Local\Programs\Python\Python37-32\lib\site-packages\proxy\proxy.py", line 439, in main
    with Proxy(input_args=input_args, **opts):
  File "C:\Users\dpgorman\AppData\Local\Programs\Python\Python37-32\lib\site-packages\proxy\proxy.py", line 132, in __init__
    self.flags = Proxy.initialize(input_args, **opts)
  File "C:\Users\dpgorman\AppData\Local\Programs\Python\Python37-32\lib\site-packages\proxy\proxy.py", line 199, in initialize
    'plugins', args.plugins.split(text_(COMMA)))]
  File "C:\Users\dpgorman\AppData\Local\Programs\Python\Python37-32\lib\site-packages\proxy\proxy.py", line 323, in load_plugins
    klass, module_name = Proxy.import_plugin(plugin_)
  File "C:\Users\dpgorman\AppData\Local\Programs\Python\Python37-32\lib\site-packages\proxy\proxy.py", line 346, in import_plugin
    module_name, klass_name = plugin_.rsplit(text_(DOT), 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by Kuruyia** [comment]
There was an issue in how I passed the plugins to proxy.py that was brought up in v2.3.0, this should be fixed now.
Can you pull the latest changes and verify?

**Comment by Kuruyia** [comment]
Considered fixed, thanks for reporting!
